// 생성: 2026-10-08 13:33 KST
// 문항 형식은 PRD 4.1, 규칙은 PRD 4.2를 따른다. 작성할 때 정답은 항상 choices[0], answer는 0이다.
const QUESTIONS = [
  {
    id: "kh-01",
    category: "한국사",
    question: "광개토왕의 업적을 기록한 광개토왕릉비를 세운 고구려의 왕은?",
    choices: ["장수왕", "소수림왕", "고국원왕", "미천왕"],
    answer: 0,
    explanation: "광개토왕릉비는 광개토왕의 아들인 고구려 장수왕이 세웠다.",
    source: { name: "한국민족문화대백과사전, 광개토왕릉비", url: "https://encykorea.aks.ac.kr/Article/E0005058" },
  },
  {
    id: "kh-02",
    category: "한국사",
    question: "1443년에 완성된 훈민정음을 만든 조선의 왕은?",
    choices: ["세종", "태종", "세조", "성종"],
    answer: 0,
    explanation: "한글(훈민정음)은 조선 제4대 왕 세종이 만든 것으로 전하며, 1443년에 완성되었다.",
    source: { name: "브리태니커, Hangul", url: "https://www.britannica.com/topic/Hangul-Korean-alphabet" },
  },
  {
    id: "kh-03",
    category: "한국사",
    question: "고려를 세운 인물은?",
    choices: ["왕건", "궁예", "견훤", "김부"],
    answer: 0,
    explanation: "왕건(태조)은 고려를 세웠으며, 서양의 이름 Korea는 고려에서 나왔다.",
    source: { name: "브리태니커, Wang Kon", url: "https://www.britannica.com/biography/Wang-Kon" },
  },
  {
    id: "kh-04",
    category: "한국사",
    question: "조선을 세우고 한양(지금의 서울)에 도읍을 정한 인물은?",
    choices: ["이성계", "이방원", "최영", "정몽주"],
    answer: 0,
    explanation: "이성계는 조선(1392~1910)을 세우고 도읍을 한양으로 정했다.",
    source: { name: "브리태니커, Yi Seong-Gye", url: "https://www.britannica.com/biography/Yi-Seong-Gye" },
  },
  {
    id: "kh-05",
    category: "한국사",
    question: "1592년 한산도대첩에서 전라좌수사로 조선 수군을 이끈 장수는?",
    choices: ["이순신", "권율", "김시민", "곽재우"],
    answer: 0,
    explanation: "한산도대첩은 1592년 7월 이순신 등이 이끈 조선 수군이 일본 수군을 무찌른 해전이다.",
    source: { name: "한국민족문화대백과사전, 한산도대첩", url: "https://encykorea.aks.ac.kr/Article/E0061676" },
  },
  {
    id: "kh-06",
    category: "한국사",
    question: "3·1 운동이 일어난 해는?",
    choices: ["1919년", "1910년", "1926년", "1945년"],
    answer: 0,
    explanation: "3·1 운동은 1919년 3월 1일을 기해 일어난 거족적인 독립만세운동이다.",
    source: { name: "한국민족문화대백과사전, 3·1운동", url: "https://encykorea.aks.ac.kr/Article/E0026772" },
  },
  {
    id: "kh-07",
    category: "한국사",
    question: "1919년 4월 대한민국 임시정부가 처음 수립된 도시는?",
    choices: ["상하이", "충칭", "베이징", "도쿄"],
    answer: 0,
    explanation: "대한민국 임시정부는 1919년 4월 중국 상하이에서 수립되었다.",
    source: { name: "한국민족문화대백과사전, 대한민국 임시정부", url: "https://encykorea.aks.ac.kr/Article/E0015017" },
  },
  {
    id: "kh-08",
    category: "한국사",
    question: "팔만대장경 목판을 보관하는 장경판전이 있는 사찰은?",
    choices: ["해인사", "불국사", "송광사", "통도사"],
    answer: 0,
    explanation: "해인사 장경판전은 팔만대장경 목판을 보관하려고 지은 건물로 세계유산이다.",
    source: { name: "유네스코 세계유산센터, Haeinsa Temple Janggyeong Panjeon", url: "https://whc.unesco.org/en/list/737" },
  },
  {
    id: "kh-09",
    category: "한국사",
    question: "녹두장군이라 불린 동학농민군의 지도자는?",
    choices: ["전봉준", "최제우", "김옥균", "홍경래"],
    answer: 0,
    explanation: "전봉준은 동학 접주이자 동학농민군 대장을 지낸 지도자로, 녹두장군이라 불렸다.",
    source: { name: "한국민족문화대백과사전, 전봉준", url: "https://encykorea.aks.ac.kr/Article/E0049437" },
  },
  {
    id: "kh-10",
    category: "한국사",
    question: "신라의 수도였으며 지금도 신라 유적이 많이 남아 있는 도시는?",
    choices: ["경주", "부여", "공주", "개성"],
    answer: 0,
    explanation: "경주 역사유적지구는 신라의 수도였던 경주의 가치를 보여 주는 세계유산이다.",
    source: { name: "유네스코 세계유산센터, Gyeongju Historic Areas", url: "https://whc.unesco.org/en/list/976" },
  },
  {
    id: "wg-01",
    category: "세계지리",
    question: "오스트레일리아의 수도는?",
    choices: ["캔버라", "시드니", "멜버른", "퍼스"],
    answer: 0,
    explanation: "캔버라는 오스트레일리아의 수도다.",
    source: { name: "브리태니커, Canberra", url: "https://www.britannica.com/place/Canberra" },
  },
  {
    id: "wg-02",
    category: "세계지리",
    question: "캐나다의 수도는?",
    choices: ["오타와", "토론토", "밴쿠버", "몬트리올"],
    answer: 0,
    explanation: "오타와는 캐나다의 수도다.",
    source: { name: "브리태니커, Ottawa", url: "https://www.britannica.com/place/Ottawa" },
  },
  {
    id: "wg-03",
    category: "세계지리",
    question: "이집트의 수도는?",
    choices: ["카이로", "알렉산드리아", "룩소르", "아스완"],
    answer: 0,
    explanation: "카이로는 이집트의 수도이며 아프리카의 큰 도시 가운데 하나다.",
    source: { name: "브리태니커, Cairo", url: "https://www.britannica.com/place/Cairo" },
  },
  {
    id: "wg-04",
    category: "세계지리",
    question: "사하라 사막이 있는 대륙은?",
    choices: ["아프리카", "아시아", "오세아니아", "남아메리카"],
    answer: 0,
    explanation: "사하라 사막은 아프리카 북부의 거의 전부를 차지한다.",
    source: { name: "브리태니커, Sahara", url: "https://www.britannica.com/place/Sahara-desert-Africa" },
  },
  {
    id: "wg-05",
    category: "세계지리",
    question: "안데스산맥이 있는 대륙은?",
    choices: ["남아메리카", "북아메리카", "아시아", "유럽"],
    answer: 0,
    explanation: "안데스산맥은 남아메리카의 산계로, 대륙의 남쪽 끝에서 북쪽 해안까지 이어진다.",
    source: { name: "브리태니커, Andes Mountains", url: "https://www.britannica.com/place/Andes-Mountains" },
  },
  {
    id: "wg-06",
    category: "세계지리",
    question: "아마존강이 흘러드는 바다는?",
    choices: ["대서양", "태평양", "인도양", "카리브해"],
    answer: 0,
    explanation: "아마존강은 브라질 북동부 해안에서 대서양으로 흘러든다.",
    source: { name: "브리태니커, Amazon River", url: "https://www.britannica.com/place/Amazon-River" },
  },
  {
    id: "wg-07",
    category: "세계지리",
    question: "나일강이 흘러드는 바다는?",
    choices: ["지중해", "홍해", "아라비아해", "흑해"],
    answer: 0,
    explanation: "나일강은 아프리카 북동부를 지나 북쪽으로 흘러 지중해로 들어간다.",
    source: { name: "브리태니커, Nile River", url: "https://www.britannica.com/place/Nile-River" },
  },
  {
    id: "wg-08",
    category: "세계지리",
    question: "에베레스트산이 속한 산맥은?",
    choices: ["히말라야산맥", "알프스산맥", "로키산맥", "안데스산맥"],
    answer: 0,
    explanation: "에베레스트산은 네팔과 중국 티베트 자치구 경계의 히말라야산맥에 있다.",
    source: { name: "브리태니커, Mount Everest", url: "https://www.britannica.com/place/Mount-Everest" },
  },
  {
    id: "wg-09",
    category: "세계지리",
    question: "킬리만자로산이 있는 나라는?",
    choices: ["탄자니아", "케냐", "에티오피아", "우간다"],
    answer: 0,
    explanation: "킬리만자로산은 탄자니아 북동부, 케냐 국경 가까이에 있는 화산 산괴다.",
    source: { name: "브리태니커, Kilimanjaro", url: "https://www.britannica.com/place/Kilimanjaro" },
  },
  {
    id: "wg-10",
    category: "세계지리",
    question: "경도 0도인 본초 자오선의 기준이 된 천문대가 있는 영국의 지역은?",
    choices: ["그리니치", "옥스퍼드", "케임브리지", "에든버러"],
    answer: 0,
    explanation: "그리니치 왕립 천문대의 에어리 자오환이 세계의 경도 0도를 정했다.",
    source: { name: "로열 뮤지엄스 그리니치, What is the Prime Meridian", url: "https://www.rmg.co.uk/stories/time/what-prime-meridian-why-it-greenwich" },
  },
];
