// 생성: 2026-10-08 13:33 KST
// 문항 형식은 PRD 4.1, 규칙은 PRD 4.2를 따른다. 작성할 때 정답은 항상 choices[0], answer는 0이다.
const QUESTIONS = [
  {
    id: "kh-01",
    category: "한국사",
    question: "광개토왕의 업적을 기록한 광개토왕릉비를 세운 고구려의 왕은?",
    choices: ["장수왕", "소수림왕", "고국원왕", "미천왕"],
    answer: 0,
    explanation: "광개토왕릉비는 광개토왕의 아들인 고구려 장수왕이 세웠다.",
    source: { name: "한국민족문화대백과사전, 광개토왕릉비", url: "https://encykorea.aks.ac.kr/Article/E0005058" },
  },
  {
    id: "kh-02",
    category: "한국사",
    question: "1443년에 완성된 훈민정음을 만든 조선의 왕은?",
    choices: ["세종", "태종", "세조", "성종"],
    answer: 0,
    explanation: "한글(훈민정음)은 조선 제4대 왕 세종이 만든 것으로 전하며, 1443년에 완성되었다.",
    source: { name: "브리태니커, Hangul", url: "https://www.britannica.com/topic/Hangul-Korean-alphabet" },
  },
  {
    id: "kh-03",
    category: "한국사",
    question: "고려를 세운 인물은?",
    choices: ["왕건", "궁예", "견훤", "김부"],
    answer: 0,
    explanation: "왕건(태조)은 고려를 세웠으며, 서양의 이름 Korea는 고려에서 나왔다.",
    source: { name: "브리태니커, Wang Kon", url: "https://www.britannica.com/biography/Wang-Kon" },
  },
  {
    id: "kh-04",
    category: "한국사",
    question: "조선을 세우고 한양(지금의 서울)에 도읍을 정한 인물은?",
    choices: ["이성계", "이방원", "최영", "정몽주"],
    answer: 0,
    explanation: "이성계는 조선(1392~1910)을 세우고 도읍을 한양으로 정했다.",
    source: { name: "브리태니커, Yi Seong-Gye", url: "https://www.britannica.com/biography/Yi-Seong-Gye" },
  },
  {
    id: "kh-05",
    category: "한국사",
    question: "1592년 한산도대첩에서 전라좌수사로 조선 수군을 이끈 장수는?",
    choices: ["이순신", "권율", "김시민", "곽재우"],
    answer: 0,
    explanation: "한산도대첩은 1592년 7월 이순신 등이 이끈 조선 수군이 일본 수군을 무찌른 해전이다.",
    source: { name: "한국민족문화대백과사전, 한산도대첩", url: "https://encykorea.aks.ac.kr/Article/E0061676" },
  },
  {
    id: "kh-06",
    category: "한국사",
    question: "3·1 운동이 일어난 해는?",
    choices: ["1919년", "1910년", "1926년", "1945년"],
    answer: 0,
    explanation: "3·1 운동은 1919년 3월 1일을 기해 일어난 거족적인 독립만세운동이다.",
    source: { name: "한국민족문화대백과사전, 3·1운동", url: "https://encykorea.aks.ac.kr/Article/E0026772" },
  },
  {
    id: "kh-07",
    category: "한국사",
    question: "1919년 4월 대한민국 임시정부가 처음 수립된 도시는?",
    choices: ["상하이", "충칭", "베이징", "도쿄"],
    answer: 0,
    explanation: "대한민국 임시정부는 1919년 4월 중국 상하이에서 수립되었다.",
    source: { name: "한국민족문화대백과사전, 대한민국 임시정부", url: "https://encykorea.aks.ac.kr/Article/E0015017" },
  },
  {
    id: "kh-08",
    category: "한국사",
    question: "팔만대장경 목판을 보관하는 장경판전이 있는 사찰은?",
    choices: ["해인사", "불국사", "송광사", "통도사"],
    answer: 0,
    explanation: "해인사 장경판전은 팔만대장경 목판을 보관하려고 지은 건물로 세계유산이다.",
    source: { name: "유네스코 세계유산센터, Haeinsa Temple Janggyeong Panjeon", url: "https://whc.unesco.org/en/list/737" },
  },
  {
    id: "kh-09",
    category: "한국사",
    question: "녹두장군이라 불린 동학농민군의 지도자는?",
    choices: ["전봉준", "최제우", "김옥균", "홍경래"],
    answer: 0,
    explanation: "전봉준은 동학 접주이자 동학농민군 대장을 지낸 지도자로, 녹두장군이라 불렸다.",
    source: { name: "한국민족문화대백과사전, 전봉준", url: "https://encykorea.aks.ac.kr/Article/E0049437" },
  },
  {
    id: "kh-10",
    category: "한국사",
    question: "신라의 수도였으며 지금도 신라 유적이 많이 남아 있는 도시는?",
    choices: ["경주", "부여", "공주", "개성"],
    answer: 0,
    explanation: "경주 역사유적지구는 신라의 수도였던 경주의 가치를 보여 주는 세계유산이다.",
    source: { name: "유네스코 세계유산센터, Gyeongju Historic Areas", url: "https://whc.unesco.org/en/list/976" },
  },
  {
    id: "wg-01",
    category: "세계지리",
    question: "오스트레일리아의 수도는?",
    choices: ["캔버라", "시드니", "멜버른", "퍼스"],
    answer: 0,
    explanation: "캔버라는 오스트레일리아의 수도다.",
    source: { name: "브리태니커, Canberra", url: "https://www.britannica.com/place/Canberra" },
  },
  {
    id: "wg-02",
    category: "세계지리",
    question: "캐나다의 수도는?",
    choices: ["오타와", "토론토", "밴쿠버", "몬트리올"],
    answer: 0,
    explanation: "오타와는 캐나다의 수도다.",
    source: { name: "브리태니커, Ottawa", url: "https://www.britannica.com/place/Ottawa" },
  },
  {
    id: "wg-03",
    category: "세계지리",
    question: "이집트의 수도는?",
    choices: ["카이로", "알렉산드리아", "룩소르", "아스완"],
    answer: 0,
    explanation: "카이로는 이집트의 수도이며 아프리카의 큰 도시 가운데 하나다.",
    source: { name: "브리태니커, Cairo", url: "https://www.britannica.com/place/Cairo" },
  },
  {
    id: "wg-04",
    category: "세계지리",
    question: "사하라 사막이 있는 대륙은?",
    choices: ["아프리카", "아시아", "오세아니아", "남아메리카"],
    answer: 0,
    explanation: "사하라 사막은 아프리카 북부의 거의 전부를 차지한다.",
    source: { name: "브리태니커, Sahara", url: "https://www.britannica.com/place/Sahara-desert-Africa" },
  },
  {
    id: "wg-05",
    category: "세계지리",
    question: "안데스산맥이 있는 대륙은?",
    choices: ["남아메리카", "북아메리카", "아시아", "유럽"],
    answer: 0,
    explanation: "안데스산맥은 남아메리카의 산계로, 대륙의 남쪽 끝에서 북쪽 해안까지 이어진다.",
    source: { name: "브리태니커, Andes Mountains", url: "https://www.britannica.com/place/Andes-Mountains" },
  },
  {
    id: "wg-06",
    category: "세계지리",
    question: "아마존강이 흘러드는 바다는?",
    choices: ["대서양", "태평양", "인도양", "카리브해"],
    answer: 0,
    explanation: "아마존강은 브라질 북동부 해안에서 대서양으로 흘러든다.",
    source: { name: "브리태니커, Amazon River", url: "https://www.britannica.com/place/Amazon-River" },
  },
  {
    id: "wg-07",
    category: "세계지리",
    question: "나일강이 흘러드는 바다는?",
    choices: ["지중해", "홍해", "아라비아해", "흑해"],
    answer: 0,
    explanation: "나일강은 아프리카 북동부를 지나 북쪽으로 흘러 지중해로 들어간다.",
    source: { name: "브리태니커, Nile River", url: "https://www.britannica.com/place/Nile-River" },
  },
  {
    id: "wg-08",
    category: "세계지리",
    question: "에베레스트산이 속한 산맥은?",
    choices: ["히말라야산맥", "알프스산맥", "로키산맥", "안데스산맥"],
    answer: 0,
    explanation: "에베레스트산은 네팔과 중국 티베트 자치구 경계의 히말라야산맥에 있다.",
    source: { name: "브리태니커, Mount Everest", url: "https://www.britannica.com/place/Mount-Everest" },
  },
  {
    id: "wg-09",
    category: "세계지리",
    question: "킬리만자로산이 있는 나라는?",
    choices: ["탄자니아", "케냐", "에티오피아", "우간다"],
    answer: 0,
    explanation: "킬리만자로산은 탄자니아 북동부, 케냐 국경 가까이에 있는 화산 산괴다.",
    source: { name: "브리태니커, Kilimanjaro", url: "https://www.britannica.com/place/Kilimanjaro" },
  },
  {
    id: "wg-10",
    category: "세계지리",
    question: "경도 0도인 본초 자오선의 기준이 된 천문대가 있는 영국의 지역은?",
    choices: ["그리니치", "옥스퍼드", "케임브리지", "에든버러"],
    answer: 0,
    explanation: "그리니치 왕립 천문대의 에어리 자오환이 세계의 경도 0도를 정했다.",
    source: { name: "로열 뮤지엄스 그리니치, What is the Prime Meridian", url: "https://www.rmg.co.uk/stories/time/what-prime-meridian-why-it-greenwich" },
  },
  {
    id: "sc-01",
    category: "과학",
    question: "물 분자의 화학식은?",
    choices: ["H2O", "CO2", "O2", "NaCl"],
    answer: 0,
    explanation: "물 분자의 구조는 H2O로 나타낸다.",
    source: { name: "브리태니커, Water", url: "https://www.britannica.com/science/water" },
  },
  {
    id: "sc-02",
    category: "과학",
    question: "식물 세포에서 광합성이 일어나는 세포 소기관은?",
    choices: ["엽록체", "미토콘드리아", "리보솜", "골지체"],
    answer: 0,
    explanation: "엽록체는 식물과 녹조류의 세포 안에서 광합성이 일어나는 구조다.",
    source: { name: "브리태니커, Chloroplast", url: "https://www.britannica.com/science/chloroplast" },
  },
  {
    id: "sc-03",
    category: "과학",
    question: "공전 궤도를 기준으로 태양에 가장 가까운 행성은?",
    choices: ["수성", "금성", "지구", "화성"],
    answer: 0,
    explanation: "수성은 태양에 가장 가까운 행성이며, 태양계에서 가장 작은 행성이다.",
    source: { name: "NASA, Mercury", url: "https://science.nasa.gov/mercury/" },
  },
  {
    id: "sc-04",
    category: "과학",
    question: "1953년 DNA를 두 가닥이 꼬인 이중 나선 구조로 설명한 두 과학자는?",
    choices: ["왓슨과 크릭", "멘델과 모건", "보어와 러더퍼드", "다윈과 월리스"],
    answer: 0,
    explanation: "1953년 왓슨과 크릭은 DNA를 상보적 염기쌍으로 이어진 두 가닥으로 설명했다.",
    source: { name: "브리태니커, DNA", url: "https://www.britannica.com/science/DNA" },
  },
  {
    id: "sc-05",
    category: "과학",
    question: "원소를 원자량 순으로 배열해 주기율표를 만든 러시아의 화학자는?",
    choices: ["멘델레예프", "아보가드로", "베르셀리우스", "라부아지에"],
    answer: 0,
    explanation: "멘델레예프는 원소를 원자량 순으로 배열해 성질이 주기적으로 되풀이됨을 찾아냈다.",
    source: { name: "브리태니커, Dmitri Mendeleev", url: "https://www.britannica.com/biography/Dmitri-Mendeleev" },
  },
  {
    id: "sc-06",
    category: "과학",
    question: "페니실린을 발견한 스코틀랜드의 세균학자는?",
    choices: ["플레밍", "파스퇴르", "코흐", "리스터"],
    answer: 0,
    explanation: "알렉산더 플레밍은 페니실린 발견으로 가장 잘 알려진 스코틀랜드의 세균학자다.",
    source: { name: "브리태니커, Alexander Fleming", url: "https://www.britannica.com/biography/Alexander-Fleming" },
  },
  {
    id: "sc-07",
    category: "과학",
    question: "척추동물의 적혈구 안에서 산소를 조직으로 나르는 단백질은?",
    choices: ["헤모글로빈", "인슐린", "케라틴", "콜라겐"],
    answer: 0,
    explanation: "헤모글로빈은 철을 포함한 혈액 단백질로, 산소를 조직으로 운반한다.",
    source: { name: "브리태니커, Hemoglobin", url: "https://www.britannica.com/science/hemoglobin" },
  },
  {
    id: "sc-08",
    category: "과학",
    question: "현재 지구 대기의 분자 조성에서 비율이 가장 높은 기체는?",
    choices: ["질소", "산소", "아르곤", "이산화 탄소"],
    answer: 0,
    explanation: "현재 지구 대기에서 비율이 가장 높은 분자는 질소(N2)다.",
    source: { name: "브리태니커, Atmosphere", url: "https://www.britannica.com/science/atmosphere" },
  },
  {
    id: "sc-09",
    category: "과학",
    question: "운동의 3법칙과 만유인력의 법칙을 정리한 과학자는?",
    choices: ["뉴턴", "갈릴레이", "케플러", "하위헌스"],
    answer: 0,
    explanation: "뉴턴의 운동 3법칙은 만유인력의 법칙을 세우는 바탕이 되었다.",
    source: { name: "브리태니커, Isaac Newton", url: "https://www.britannica.com/biography/Isaac-Newton" },
  },
  {
    id: "sc-10",
    category: "과학",
    question: "원자를 이루는 입자 가운데 전기 전하를 띠지 않는 것은?",
    choices: ["중성자", "양성자", "전자", "원자핵"],
    answer: 0,
    explanation: "중성자는 전기 전하가 없는 입자다.",
    source: { name: "브리태니커, Neutron", url: "https://www.britannica.com/science/neutron" },
  },
  {
    id: "ac-01",
    category: "예술과 문화",
    question: "「모나리자」를 그린 화가는?",
    choices: ["레오나르도 다빈치", "미켈란젤로", "라파엘로", "보티첼리"],
    answer: 0,
    explanation: "「모나리자」는 레오나르도 다빈치가 나무판에 유채로 그린 그림으로, 루브르에 있다.",
    source: { name: "브리태니커, Mona Lisa", url: "https://www.britannica.com/topic/Mona-Lisa-painting" },
  },
  {
    id: "ac-02",
    category: "예술과 문화",
    question: "1889년 생레미에서 「별이 빛나는 밤」을 그린 화가는?",
    choices: ["빈센트 반 고흐", "폴 고갱", "클로드 모네", "폴 세잔"],
    answer: 0,
    explanation: "「별이 빛나는 밤」은 반 고흐가 1889년 6월 생레미에서 그린 유화다.",
    source: { name: "뉴욕 현대미술관(MoMA), The Starry Night", url: "https://www.moma.org/collection/works/79802" },
  },
  {
    id: "ac-03",
    category: "예술과 문화",
    question: "교향곡 제5번 다단조(작품 67)를 작곡한 사람은?",
    choices: ["베토벤", "모차르트", "하이든", "슈베르트"],
    answer: 0,
    explanation: "교향곡 제5번 다단조, 작품 67은 베토벤의 교향곡이다.",
    source: { name: "브리태니커, Symphony No. 5 in C Minor, Op. 67", url: "https://www.britannica.com/topic/Symphony-No-5-in-C-Minor-Op-67" },
  },
  {
    id: "ac-04",
    category: "예술과 문화",
    question: "희곡 「로미오와 줄리엣」을 쓴 작가는?",
    choices: ["셰익스피어", "몰리에르", "괴테", "입센"],
    answer: 0,
    explanation: "「로미오와 줄리엣」은 윌리엄 셰익스피어가 1594~96년 무렵에 쓴 희곡이다.",
    source: { name: "브리태니커, Romeo and Juliet", url: "https://www.britannica.com/topic/Romeo-and-Juliet" },
  },
  {
    id: "ac-05",
    category: "예술과 문화",
    question: "소리꾼 한 명과 북을 치는 고수가 함께 이야기를 노래로 엮어 가는 한국의 전통 음악은?",
    choices: ["판소리", "가곡", "종묘제례악", "산조"],
    answer: 0,
    explanation: "판소리는 소리꾼과 고수가 함께 공연하는 이야기 음악으로, 인류무형문화유산이다.",
    source: { name: "유네스코 무형유산, Pansori epic chant", url: "https://ich.unesco.org/en/RL/pansori-epic-chant-00070" },
  },
  {
    id: "ac-06",
    category: "예술과 문화",
    question: "「씨름」이 실린 《단원 풍속도첩》을 그린 화가는?",
    choices: ["김홍도", "신윤복", "정선", "장승업"],
    answer: 0,
    explanation: "「씨름」은 김홍도의 풍속화 특징을 대표하는 명품으로 꼽힌다.",
    source: { name: "국립중앙박물관, 씨름, 《단원 풍속도첩》", url: "https://www.museum.go.kr/MUSEUM/contents/M0502000000.do?schM=view&searchId=search&relicId=551" },
  },
  {
    id: "ac-07",
    category: "예술과 문화",
    question: "스페인 바르셀로나의 사그라다 파밀리아 성당을 주로 설계한 건축가는?",
    choices: ["안토니 가우디", "르코르뷔지에", "프랭크 게리", "오스카 니마이어"],
    answer: 0,
    explanation: "사그라다 파밀리아는 카탈루냐의 건축가 안토니 가우디가 주로 설계한 성당이다.",
    source: { name: "브리태니커, Sagrada Família", url: "https://www.britannica.com/topic/Sagrada-Familia" },
  },
  {
    id: "ac-08",
    category: "예술과 문화",
    question: "발레 「백조의 호수」를 작곡한 사람은?",
    choices: ["차이콥스키", "라흐마니노프", "스트라빈스키", "프로코피예프"],
    answer: 0,
    explanation: "「백조의 호수」는 러시아의 작곡가 차이콥스키가 1876년에 작곡한 발레다.",
    source: { name: "브리태니커, Swan Lake", url: "https://www.britannica.com/topic/Swan-Lake-ballet-by-Tchaikovsky" },
  },
  {
    id: "ac-09",
    category: "예술과 문화",
    question: "조각 「생각하는 사람」을 만든 조각가는?",
    choices: ["로댕", "카노바", "부르델", "베르니니"],
    answer: 0,
    explanation: "「생각하는 사람」은 로댕의 대표작으로, 파리 로댕 미술관 정원에 있다.",
    source: { name: "브리태니커, Rodin Museum", url: "https://www.britannica.com/topic/Rodin-Museum" },
  },
  {
    id: "ac-10",
    category: "예술과 문화",
    question: "탈을 쓴 연희자가 춤, 노래, 대사로 사회 문제를 익살스럽게 다루는 한국의 전통 공연은?",
    choices: ["탈춤", "꼭두각시놀음", "강강술래", "줄타기"],
    answer: 0,
    explanation: "탈춤은 춤, 음악, 연극을 아우르며 탈을 쓴 연희자가 사회 문제를 다루는 공연이다.",
    source: { name: "유네스코 무형유산, Talchum", url: "https://ich.unesco.org/en/RL/talchum-mask-dance-drama-in-the-republic-of-korea-01742" },
  },
];
